language: java
before_script:
- bash pull.sh
after_success:
- bash push.sh
env:
  global:
    secure: SWRolbRLggD0M2JDINGYccqKnGHlOiAjXC1DdSHpSVKavLv0xzA3Y1aWHYqiayXUivBqyQF6k+A1EshMN2QUdcwFX6M4bOSoUnK3Kpzyvu8HK08sufTTIy7+0txpoZuTN2Lr/pH7M0TJXoNkGwRXjndVrFUBzUMHmkl66u8M0/sYkri0dgiWvBuwG6k45feICQLl4ujBFQY+9NonqjUE1z6SRTUte79ZKdgVbnjJftCahHOEmwu/dtc4WQBSXPS7rFJ0/tHyQ721s+QrVZDSYjRX4f8J8hXGsw91R0+pao2fuU96SEgm7twJij2bG96RbBB8nFugQfE9VhtBcqc+HjRpDtRSda44pa4oD7vsFYKuRU6JUB989aVacD9SZTvb8RO8lwD9ZkZvIQfaVQR69WpE96MOgVSeCZ10bJfXNU6cWhAqNZHdEcBKggHO4ToNlkyg3QcoCwL34PWJSf2VDoY1Hcme4iL+U+GNTyO72XesbOK4Wi1Ss59jldhRBTiffRaUQOTK+BiyRcNuOkpqEYefOAzitydTob880Na/eLEAyOLJwbktbODwtfG0HwFDxYPEtzpuQrUFr2PpoEdPRfqDyeai6x6RwmvZuCi/5psEA+zK1TkFvyS22vNpoqcOftiFonLv2cSCsrWpgF5X4DTH8txEdvOU1K4OFe1HVk4=
